services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: dockerfile
    networks:
        - local
    ports:
      - "80"
    environment:
      - RUST_LOG=info
      - LEPTOS_SITE_ADDR=0.0.0.0:80
      - LEPTOS_SITE_ROOT=site
    restart: unless-stopped

networks:
    local:
        external: true